name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag sailplay-sdk-php-cli:$(date +%s)
    - name: docker run
      run: docker run --rm --volume "$(pwd):/home/dev/app/" sailplay-sdk-php-cli composer check
