name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./bin/docker_build.bash
    - name: docker run composer install
      run: ./bin/run.bash composer install --prefer-dist --no-progress
    - name: docker run composer check
      run: ./bin/run.bash composer check
