name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Phpstan analyse code
      run: composer stan
      
    - name: PHP CodeSniffer check code
      run: composer sniffer-check
    
    - name: php-cs-fixer check code
      run: composer fixer-check
      
    - name: phpunit tests
      run: composer unit
